# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "setup", "~>5.2"
gem "notifier", "~>0.5"

gem "hoe-deveiate", "~>0.7", :group => [:development, :test]
gem "hoe-manualgen", "~>0.3.0", :group => [:development, :test]
gem "hoe-highline", "~>0.2", :group => [:development, :test]
gem "hoe-mercurial", "~>1.4", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-doofus", "~>1.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-rubygems", "~>1.0", :group => [:development, :test]
gem "hoe-seattlerb", "~>1.3", :group => [:development, :test]
gem "hoe-version", "~>1.2", :group => [:development, :test]
gem "hoe-reek", "~>1.0", :group => [:development, :test]
gem "hoe-roodi", "~>1.0", :group => [:development, :test]
gem "ZenTest", "~>4.11", :group => [:development, :test]
gem "rake", "~>10.0", :group => [:development, :test]
gem "simplecov", "~>0.7", :group => [:development, :test]
gem "coveralls", "~>0.8", :group => [:development, :test]
gem "gem-release", "~>0.7", :group => [:development, :test]
gem "indexer", "~>0.3", :group => [:development, :test]
gem "reek", "~>3.3", :group => [:development, :test]
gem "roodi", "~>5.0", :group => [:development, :test]
gem "rubocop", "~>0.34", :group => [:development, :test]
gem "hoe", "~>3.14", :group => [:development, :test]

# vim: syntax=ruby
